### ISSUE TITLE
Enable the model validation to prevent storing invalid resource artifacts through REST API

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-resource-server#60]
The model validator should be the gatekeeper to prevent invalid resources from entering CEDAR through the REST API call (e.g., POST or PUT command)

Requires metadatacenter/cedar-model-validation-library#107
Requires metadatacenter/cedar-model-validation-library#114

**Comment by martinjoconnor** [comment]
We are backing off on this for the moment until we are at zero validation errors for all schema and instance artifacts.

**Comment by johardi** [comment]
I'm trying to push back here. I think we should enable this as soon as possible without waiting for the instance validation. The reason is we need to have perfectly valid templates (and elements) to be able to validate the instances; we can't do this if we keep storing invalid templates/elements.

**Comment by martinjoconnor** [comment]
True - though we are waiting on Oxford here because they still have invalid templates in the system. 

Perhaps email them to see if we can delete the current broken versions. Nobody is likely using them.

A complication here is that Debra has added new extensions to the model to handle default values and value reordering (https://github.com/metadatacenter/cedar-model-validation-library/issues/118 and https://github.com/metadatacenter/cedar-model-validation-library/issues/119), which we will also need to handle.

We may need some sort of flag for development to allow experimentation with new extensions. We should discuss tomorrow.

**Comment by martinjoconnor** [comment]
Now have flag to turn on and off validation at REST level:

https://github.com/metadatacenter/cedar-model-validation-library/issues/124

Not yet on for production.
