### ISSUE TITLE
Resource server throwing error if saving twice really quickly

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-resource-server#7]
Steps to reproduce:
- Go to "Populate" page
- Click the "Save" button twice with the speed of a double-click
- The second save will fail, throwing the following error:

Status: 500, Internal Server Error
URL: https://resource.metadatacenter.orgx/templates/https%3A%2F%2Frepo.metadatacenter.orgx%2Ftemplates%2Fbe2146e2-b327-4f7f-bb5c-f9774f6ab78d
Method: PUT

Message: Failed to remove resource https://repo.metadatacenter.orgx/templates/be2146e2-b327-4f7f-bb5c-f9774f6ab78d from the index
Exception: java.io.IOException: Failed to remove resource https://repo.metadatacenter.orgx/templates/be2146e2-b327-4f7f-bb5c-f9774f6ab78d from the index

org.metadatacenter.cedar.resource.search.elasticsearch.ElasticsearchService.removeFromIndex(ElasticsearchService.java:125)<br />org.metadatacenter.cedar.resource.search.SearchService.removeResourceFromIndex(SearchService.java:67)<br />org.metadatacenter.cedar.resource.search.SearchService.updateIndexedResource(SearchService.java:84)<br />org.metadatacenter.cedar.resource.search.SearchService.updateIndexedResource(SearchService.java:92)<br />controllers.AbstractResourceServerController.executeResourcePutByProxy(AbstractResourceServerController.java:438)<br />controllers.TemplateServerController.updateTemplate(TemplateServerController.java:56)<br 
...

**Comment by egyedia** [comment]
I tried to fix this.

The error was caused by ElasticsearchService, like it follows: 

When a document is updated, it tries to remove and to add it back again to the index.
Since the operations are not synchronous - and ElasticSearch onl;y guarantees near-real-time indexing, the document is first removed, and then another remove command is issued, which then fails. This is where the exception was thrown.

I removed the throwing of the exception, and I added a sysout message instead. This worked fine, but as a result, when pushing the Save button twice very quickly, the document was indexed twice, and it was showing up twice in the search results.

I tried to fix this by making the reindex method sychronized, but that did not help.
I thought that maybe the controllers are not singletons, so I tried making them singletons, but that did not help either - maybe they are already singletons?

It seems that there is an upsert version of the indexing mechanism:
https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-update.html
that possibly could solve this issue.

I guess we could check this out together with Marcos.

**Comment by martinjoconnor** [comment]
Interesting. We should definitely try to solve this for the release -
though I would prioritize the remaining model and permissions issues
before digging in.

**Comment by graybeal** [comment]
I'm thinking a friend and solution would be easier.

Sent from my iPhone

On Sep 6, 2016, at 7:52 PM, Attila Levente EGYEDI <notifications@github.com<mailto:notifications@github.com>> wrote:

I tried to fix this.

The error was caused by ElasticsearchService, like it follows:

When a document is updated, it tries to remove and to add it back again to the index.
Since the operations are not synchronous - and ElasticSearch onl;y guarantees near-real-time indexing, the document is first removed, and then another remove command is issued, which then fails. This is where the exception was thrown.

I removed the throwing of the exception, and I added a sysout message instead. This worked fine, but as a result, when pushing the Save button twice very quickly, the document was indexed twice, and it was showing up twice in the search results.

I tried to fix this by making the reindex method sychronized, but that did not help.
I thought that maybe the controllers are not singletons, so I tried making them singletons, but that did not help either - maybe they are already singletons?

It seems that there is an upsert version of the indexing mechanism:
https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-update.html
that possibly could solve this issue.

I guess we could check this out together with Marcos.

##

**Comment by egyedia** [comment]
The first attempt to temporarily fix this was to disable the save button until the server response arrives back.
This solution makes the situation better, but does not fully solve the problem: since the indexing is asynchronous, the server response  can get back, the button will be enabled, and if clicked again, the new request can still collide with the previous one.

So the current temporary fix was to add a 1 second delay after the server responds, and before the button is enabled again.

We will need to fix this on the server side in the next release

**Comment by egyedia** [comment]
This is related to versioning, auto-save, and asynchronous indexing as well.
We are planning to solve these in the near future.
I will move this to the backlog, since currently it is behaving well with the workaround, and we do not have a long term solution for it now.

**Comment by martinjoconnor** [comment]
No reports for several years
